[package]
name = "text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.26"

protos = { path = "../protos" }
peg = "0.7.0"
html-escape = "0.2.9"
