[package]
name = "logic"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "logic"
crate-type = ["staticlib"]

[dependencies]
dashmap = "4.0.2"
env_logger = "0.8.4"
futures = "0.3.15"
futures-cache = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.14"
reqwest = "0.11.4"
serde = { version = "1.0.126", features = ["derive"] }
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
thiserror = "1.0.26"
tokio = { version = "1.8.1", features = ["rt-multi-thread", "macros", "time"] }
chrono = "0.4.19"
regex = "1.5.4"

protos = { path = "../protos" }
text = { path = "../text" }
cache = { path = "../cache" }
config = { path = "../config" }

[dev-dependencies]
dotenv = "0.15.0"

[build-dependencies]
cbindgen = "0.19.0"

# [features]
# default = ["with-serde"]
# with-serde = ["protobuf/with-serde"]
