[package]
name = "logic"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "logic"
crate-type = ["staticlib", "cdylib"]

[dependencies]
env_logger = "0.8.4"
lazy_static = "1.4.0"
log = "0.4.14"
tokio = { version = "1.8.1", features = ["rt-multi-thread", "macros", "time"] }

protos = { path = "../protos" }
service = { path = "../service" }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19.0"

[dev-dependencies]
dotenv = "0.15.0"

[build-dependencies]
cbindgen = "0.19.0"

# [features]
# default = ["with-serde"]
# with-serde = ["protobuf/with-serde"]
